<!doctype html>
<html lang="<<lang>>">
<head>
<meta charset="utf-8">
<title><<title>></title>

<link rel="stylesheet" type="text/css" href="<<ptr>>/style.css">
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
</script>
<![endif]-->
</head>

<body>

<nav style="width: 200px;">
  <ul>
  <li><img src="<<ptr>>/imgs/weight-32.png"/></li>
  <li><a href="<<ptr>>/index.html">MySWG</a></li>
  <li><a href="<<ptr>>/lang/md.html">MD files</a></li>
  <li><a href="<<ptr>>/lang/mmd.html">MMD files</a></li>
  <li><a href="<<ptr>>/lang/tables.html">Tables</a></li>
  </ul>
</nav>

<p>&nbsp;

<div style="margin-left:200px;padding:1px 16px;height:100%;">

